
version: 2

models:
  - name: vehicle_positions
    description: "TriMet vehicle position data"
    columns:
      - name: TripDescriptor
        description: "TBD"

      - name: VehicleDescriptor
        description: "TBD"

      - name: Position
        description: "TBD"

      - name: CurrentStopSequence
        description: "TBD"

      - name: StopId
        description: "TBD"

      - name: VehicleStopStatus
        description: "TBD"

      - name: Timestamp
        description: "TBD"

      - name: CongestionLevel
        description: "TBD"

      - name: OccupancyStatus
        description: "TBD"

  - name: alerts
    description: "TriMet alerts"
    columns:
      - name: ActivePeriod
        description: "TBD"

      - name: EntitySelector
        description: "TBD"

      - name: Cause
        description: "TBD"

      - name: Effect
        description: "TBD"

      - name: Url
        description: "TBD"

      - name: HeaderTest
        description: "TBD"

      - name: DescriptionText
        description: "TBD"